# Generated by Django 4.1.7 on 2023-02-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_contact_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
