# Generated by Django 4.1.7 on 2023-02-24 08:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_alter_contact_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
