# Generated by Django 4.1.7 on 2023-02-24 14:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_alter_contact_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(default='', max_length=200)),
                ('subcategory', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('desc', ckeditor.fields.RichTextField()),
                ('product_photo', models.ImageField(upload_to='images/images')),
            ],
        ),
    ]
