# Generated by Django 4.1.7 on 2023-02-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
