# Generated by Django 4.1.7 on 2023-02-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pass1', models.CharField(max_length=255)),
                ('pass2', models.CharField(max_length=255)),
            ],
        ),
    ]
